tile_types = {
    "grass": {
        "hue_min": 35,
        "hue_max": 56,
        "saturation_min": 95,
        "saturation_max": 255,
        "brightness_min": 110,
        "brightness_max": 255,
    },
    "water": {
        "hue_min": 102,
        "hue_max": 124,
        "saturation_min": 155,
        "saturation_max": 255,
        "brightness_min": 90,
        "brightness_max": 255,
    },
    "forest": {
        "hue_min": 51 ,
        "hue_max": 74,
        "saturation_min": 36 ,
        "saturation_max": 216,
        "brightness_min": 0,
        "brightness_max": 71,
    },
    "waste": {
        "hue_min": 19 ,
        "hue_max": 24,
        "saturation_min": 67 ,
        "saturation_max": 176,
        "brightness_min": 41,
        "brightness_max": 162,
    },
    "mine": {
        "hue_min": 0 ,
        "hue_max": 32,
        "saturation_min": 0,
        "saturation_max": 133,
        "brightness_min": 0,
        "brightness_max": 43,
    },
    "farm": {
        "hue_min": 20,
        "hue_max": 29,
        "saturation_min": 95 ,
        "saturation_max": 255,
        "brightness_min": 154,
        "brightness_max": 255,
    },
}